### ISSUE TITLE
Not working inside ListView iOS

### ISSUE THREAD

**Issue by pdamco** [AndreiMisiukevich/ExpandableView#1]
When using inside ListView, this is not working for iOS and have to pass SecondaryViewHeightRequest with ListView.

**Comment by AndreiMisiukevich** [comment]
@pdamco hi, yes.. i know about this bug, but i have no idea, how to fix it now.
I tried forceUpdateSize, but it didn't help me.

Any ideas, how to fix it?

**Comment by pdamco** [comment]
@AndreiMisiukevich, No idea, I also tried forceUpdateSize but not worked for me also.

**Comment by BongaDev** [comment]
Good day, @AndreiMisiukevich  has the issue been looked at yet ?

**Comment by AndreiMisiukevich** [comment]
@BongaDev not yet.
Frankly speaking, i think, i will close it as "won't fix" as Xamarin.Forms ListView works badly with changing cell size.

But I'm open for any suggestions, how can we work around it

**Comment by BongaDev** [comment]
@AndreiMisiukevich  Will have a look at it this week and will let you know if i personally find a work around it.

**Comment by LeoJHarris** [comment]
Is this affecting android for you guys. I am having an issue where the secondaryview was not showing on tapping the primaryview which is the view cell.

**Comment by LeoJHarris** [comment]
Sorry no issues with android for me

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris 
I think, i should try to create a workaround for ViewCell... maybe latest XF provides working ForceUpdateSize method.. )

**Comment by rob-byram** [comment]
> When using inside ListView, this is not working for iOS and have to pass SecondaryViewHeightRequest with ListView.
@pdamco, do you have an example of a workaround that works? I've just run into this and either need a fix, or need to reconfigure how I'm doing my page.

**Comment by AndreiMisiukevich** [comment]
sorry, this case won't be fixed.
Expandable cells work terribly.
This controls can be used in StackLayout/AbsoluteLayout etc.

**Comment by Mike-Beers** [comment]
Does anyone know if this problem is solved by the new CollectionView?

**Comment by AndreiMisiukevich** [comment]
Try it haha )

**Comment by LeoJHarris** [comment]
@Mike-Beers I dont this this issue is with this library when putting in listview, iOS doesnt work well in any case when viewcell's resize. You can get to the native level with a custom renderer and update the underlying listview programatically: https://github.com/xamarin/Xamarin.Forms/issues/2735#issuecomment-520633123
Do this after expanding and collapsing expandableview for better resuls.

**Comment by Mike-Beers** [comment]
@AndreiMisiukevich I probably will at some point, just wanted to see if anyone else had tried first. I ended up creating stack elements from code and putting them in a scroll view. Its ugly, but it works. However I'd like to not do it that way if possible. Thanks!

**Comment by giuseppenovielli** [comment]
@AndreiMisiukevich 
try when Expand or Collapse for StackLayout call

stk.HeightRequest = 0; //Request new update view
stk.HeightRequest = -1; //Set to calculate
ForceUpdateSize(); //Calculate

into subclass of ViewCell
