### ISSUE TITLE
Slow Loading WebView

### ISSUE THREAD

**Issue by rredoh** [AndreiMisiukevich/ExpandableView#10]
Hi @AndreiMisiukevich could you check with this scenario? I need to click it multiple times until the webview show the text.. Thanks :)

```
<Expandable:ExpandableView.SecondaryViewTemplate>
     <DataTemplate>
         <WebView>
             <WebView.Source>
                         <HtmlWebViewSource Html="qwertyuiopasdfghjklzxcvbnm"/>
             </WebView.Source>
         </WebView>
     </DataTemplate>
</Expandable:ExpandableView.SecondaryViewTemplate>
```

**Comment by AndreiMisiukevich** [comment]
Hi, what the platform is?

**Comment by rredoh** [comment]
Sorry.. Forgot to mention it.. Android, but I don't have chance to test it on IOS

**Comment by AndreiMisiukevich** [comment]
@rredoh would you like to debug this case with sample?)
Unfortunately have no little time now (

**Comment by rredoh** [comment]
It's okay.. I'll try to debug it later..

**Comment by AndreiMisiukevich** [comment]
Maybe i will try to find time for check :)

**Comment by rredoh** [comment]
It's okay. Take your time. :)
Maybe it's because of the WebView. I have tried to set the WebView's height too and still nothing happen. For now I removed all the html tags and just use Label

**Comment by AndreiMisiukevich** [comment]
@rredoh have you tried to set SecondaryViewHeight ?

**Comment by rredoh** [comment]
It works and speed up the WebView loading. Thanks

**Comment by rredoh** [comment]
The rest of the problem is on the WebView then
