### ISSUE TITLE
Adding Command to PrimaryView

### ISSUE THREAD

**Issue by zoegoodwinsutton** [AndreiMisiukevich/ExpandableView#12]
Hi! I would like to add a command when a PrimaryView is tapped. I've tried adding commands within my MainView ie
```
<expandable:ExpandableView.PrimaryView>
<Button Text="{Binding ChallengeGroup6.Name}" 
TextColor="Black"
Command="{Binding OnItemCommand}"
Font="24"/>
</expandable:ExpandableView.PrimaryView>
```
However this removes the expandable action when I tap on the button. Any ideas on how to do this? Thanks for any help!

**Comment by AndreiMisiukevich** [comment]
Hi.. you will have to change IsExpanded on your side.

**Comment by AndreiMisiukevich** [comment]
Create property and bind it to IsExpanded
Change value yourself for expanding/collapsing

**Comment by zoegoodwinsutton** [comment]
Ok, thank you! Am I able to add a parameter through IsExpanded function?

**Comment by AndreiMisiukevich** [comment]
btw, check latest release i added Command and Tapped event :)
