### ISSUE TITLE
Extra bottom space with custom control

### ISSUE THREAD

**Issue by angelru** [AndreiMisiukevich/ExpandableView#14]
Hello,

I am using your control in a personalized way:

                              <expandable:ExpandableView ExpandAnimationLength="100">
                                    <expandable:ExpandableView.PrimaryView>
                                         <Label Text="Example" />
                                    </expandable:ExpandableView.PrimaryView>
                                    <expandable:ExpandableView.SecondaryViewTemplate>
                                        <DataTemplate>
                                         <controls:StackLayoutItemsView ItemsSource="{Binding Items}" />
                                        </DataTemplate>
                                    </expandable:ExpandableView.SecondaryViewTemplate>
                                </expandable:ExpandableView>

**StackLayoutItemsView** is ContenView with StackLayout BindableLayout.

If in the before code remove the control (ContenView) and I put only StackLayout BindableLayout not there is bottom space.

**Comment by AndreiMisiukevich** [comment]
Hi, provide small sample please

**Comment by angelru** [comment]
Hello @AndreiMisiukevich,
I can not reproduce the error outside of my project, so I did not put a sample.

**Comment by AndreiMisiukevich** [comment]
@angelru do you use latest version?

**Comment by angelru** [comment]
@AndreiMisiukevich  yes, I use the latest version

**Comment by AndreiMisiukevich** [comment]
@angelru please, use ** SecondaryViewHeightRequest** for setting needed height request then

so, you will have to calculate desired height yourself :)
