### ISSUE TITLE
Changing height of secondary view when contained controls change

### ISSUE THREAD

**Issue by racekarl** [AndreiMisiukevich/ExpandableView#15]
I have an ExpandableView with some form controls inside a stack layout inside the secondary view.  One of the controls opens a modal where the user selects some values, and the modal is popped when the user completes working with it.  I have some labels inside the secondary view stack layout that initially have HeightRequest = 0.  When the user closes the modal, these labels should appear (HeightRequest set to a positive value).  

The issue I am having is that the secondary view does not resize to accommodate these newly resized controls.  If I comment out the ExpandableView markup in my XAML and just have the stack layout on the view, it does resize as expected.

**Comment by AndreiMisiukevich** [comment]
Hi
Could you pls provide small sample?

**Comment by racekarl** [comment]
[ExpanderTest.zip](https://github.com/AndreiMisiukevich/ExpandableView/files/3039794/ExpanderTest.zip)

I attached a small sample project which demonstrates what I'm seeing.  On the main page are two buttons, which each navigate to a page with the same set of form controls, one inside an ExpandableView's SecondaryView and one inside a "bare" StackLayout (which is identical to what is inside the ExpandableView's SecondaryView)

To reproduce the issue, click the "Click here" button in the middle of either form, which will open a modal dialog.  Click the "Click Me" button on the dialog, which simulates a validation error.  

When you return to the form in the StackLayout page, the validation label is visible in the correct location below the button, and the rest of the controls are pushed down to accommodate its height.  

When you do the same thing from the ExpandableView page, the validation label is laid over the top of the button and the rest of the controls remain in their original positions.

**Comment by AndreiMisiukevich** [comment]
Feel free to debug this issue and make PR if you wish))

**Comment by AndreiMisiukevich** [comment]
So, you need to set secondary view heightRequest to -1 after any content updates (it will cause to redraw view)

**Comment by AndreiMisiukevich** [comment]
Hey, i added **ForceUpdateSizeCommand** and **ForceUpdateSize** method to expandable view

Just call it when you want to update size of your secondary view

You can use it with bindings as well :)
