### ISSUE TITLE
Please sample of usage with Binding from XAML

### ISSUE THREAD

**Issue by candidodmv** [AndreiMisiukevich/ExpandableView#18]
You provide a sample in this repo but don't using bindable items from xaml. Could you give us this sample? Thanks

**Comment by candidodmv** [comment]
I'm trying implements as follwed code snippet, but with no success. How to populate list data in DataTemplate of SecondaryViewTemplate ?

```
                                <expandable:ExpandableView x:Name="expandableView" BackgroundColor="Red"
                                   TouchHandlerView="{x:Reference arrow}" BindingContext="{Binding ListInParentContext}"
                                   ExpandAnimationLength="100">
                                    <expandable:ExpandableView.PrimaryView>
                                        <StackLayout Orientation="Horizontal">
                                            <Label Text="{Binding Label}" Style="{StaticResource PrimaryStyle}" VerticalTextAlignment="Center"/>
                                            <Image x:Name="arrow" Source="arrow_drop_down.png" HeightRequest="60" WidthRequest="60" HorizontalOptions="EndAndExpand"/>
                                        </StackLayout>
                                    </expandable:ExpandableView.PrimaryView>
                                    <expandable:ExpandableView.SecondaryViewTemplate>
                                        <DataTemplate>
                                            <StackLayout Padding="5">
                                                <Label Text="{Binding Title}" FontSize="Large" />
                                            </StackLayout>
                                        </DataTemplate>
                                    </expandable:ExpandableView.SecondaryViewTemplate>
                                </expandable:ExpandableView>
```

**Comment by AndreiMisiukevich** [comment]
@candidodmv just update **Title** in your model
Make sure, that Title is bindable property

**Comment by candidodmv** [comment]
I've noticed that ExpandableView extends from Stacked layout, so It's possible to use ["BindableLayout"](https://devblogs.microsoft.com/xamarin/xamarin-forms-3-5-a-little-bindable-love/) ?

**Comment by AndreiMisiukevich** [comment]
@candidodmv yes

**Comment by candidodmv** [comment]
How? Just replacing the bold part of the code snipped bellow?

                                <expandable:ExpandableView x:Name="expandableView" BackgroundColor="Red"
                                   TouchHandlerView="{x:Reference arrow}" **BindableLayout.ItemsSource="{Binding ListOfItems}"**
                                   ExpandAnimationLength="100">
                                    <expandable:ExpandableView.PrimaryView>
                                        <StackLayout Orientation="Horizontal">
                                            <Label Text="{Binding Label}" Style="{StaticResource PrimaryStyle}" VerticalTextAlignment="Center"/>
                                            <Image x:Name="arrow" Source="arrow_drop_down.png" HeightRequest="60" WidthRequest="60" HorizontalOptions="EndAndExpand"/>
                                        </StackLayout>
                                    </expandable:ExpandableView.PrimaryView>
                                    <expandable:ExpandableView.SecondaryViewTemplate>
                                        <DataTemplate>
                                            <StackLayout Padding="5">
                                                <Label Text="{Binding Title}" FontSize="Large" />
                                            </StackLayout>
                                        </DataTemplate>
                                    </expandable:ExpandableView.SecondaryViewTemplate>
                                </expandable:ExpandableView>

**Comment by AndreiMisiukevich** [comment]
@candidodmv, ah, got it. You cannot do it by this way

You set PrimaryView and SecondaryView. That's all

**Comment by candidodmv** [comment]
Thanks you so much for your support @AndreiMisiukevich.

Although doesn't make much sense, the property Secondary View Template is just a wrapper to the items, not a template as properly name suggest. So I suggest you to put a sample in readme to clarify to anyone else that have the same missconceptions about how it's works.

I don't domine the Xamarin.Forms plugins architecture must be, but i gess that this solution will works better if the SecondaryViewTemplate would be a StackedLayout, so will be able to set directly in this property the Itens and the template, insted of to have one DataTemplate inside another DataTemplate, as a said above it's don't make much sense.

If I help you with something that i have know how, will be a pleasure to help you with something else to improve this project.

my implementations become as follows:

```
<expandable:ExpandableView x:Name="expandableView" BackgroundColor="Red"
                                   TouchHandlerView="{x:Reference arrow}"
                                   ExpandAnimationLength="100">
    <expandable:ExpandableView.PrimaryView>
        <StackLayout Orientation="Horizontal">
            <Label Text="{Binding Label}" Style="{StaticResource PrimaryStyle}" VerticalTextAlignment="Center"/>
            <Image x:Name="arrow" Source="arrow_drop_down.png" HeightRequest="60" WidthRequest="60" HorizontalOptions="EndAndExpand"/>
        </StackLayout>
    </expandable:ExpandableView.PrimaryView>
    <expandable:ExpandableView.SecondaryViewTemplate>
        <DataTemplate>
            <StackLayout Padding="5" BindableLayout.ItemsSource="{Binding ListOfitems}"  Style="{StaticResource ItemWrapperStyle}">
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <Label Text="{Binding Title}" FontSize="Large" Style="{StaticResource SecondaryStyle}" />
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </StackLayout>
        </DataTemplate>
    </expandable:ExpandableView.SecondaryViewTemplate>
</expandable:ExpandableView>
```

**Comment by AndreiMisiukevich** [comment]
@candidodmv sorry, don't think so
I did it for better performance. We create secondary view only after first tap on expandable.
