### ISSUE TITLE
Next level of view

### ISSUE THREAD

**Issue by DineshkumarArunachalam** [AndreiMisiukevich/ExpandableView#19]
Hi, 
  In this sample we have upto second view. How to create a third view. can you help on this?

**Comment by AndreiMisiukevich** [comment]
Hi, try to put expandableView into another expandable view
And call ForceUpdateSize (or ForceUpdateSizeCommand) somewhere (or just change HeightRequest of first expandable to -1)

**Comment by DineshkumarArunachalam** [comment]
sorry , Actually my question add another view to the second view (like tree view
![IMG_20190429_142950_HDR](https://user-images.githubusercontent.com/33649837/56886713-35f9b100-6a8d-11e9-8290-dd9e95c2f068.jpg)
)
see the links :https://www.google.com/search?client=firefox-b-d&biw=1233&bih=613&tbm=isch&sa=1&ei=rsDGXJ6lCs30rAGDxrzADw&q=android+tree+view&oq=android+&gs_l=img.1.0.0i67j0l7j0i67j0.8226.9450..11064...0.0..0.132.843.3j5......1....1..gws-wiz-img.......35i39.WBbdRFrp5xw#imgrc=w6ymKUwEhbytPM:

**Comment by AndreiMisiukevich** [comment]
@DineshkumarArunachalam yes
As i said, you can try to add another expandable view to the root one.

exp1.SecondaryView -> StackLayout (label, label, exp2) ...

**Comment by DineshkumarArunachalam** [comment]
@AndreiMisiukevich  . Please provide any sample code to achieve it. That would be helpful.

**Comment by AndreiMisiukevich** [comment]
@DineshkumarArunachalam maybe later. Unfortunately now i have little time :(

**Comment by AndreiMisiukevich** [comment]
![nested](https://user-images.githubusercontent.com/10124814/57113798-dd593b00-6d4e-11e9-85ed-3aa169bf749b.gif)

https://github.com/AndreiMisiukevich/ExpandableView/blob/master/ExpandableViewSample/NestedExpandablePage.cs
