### ISSUE TITLE
Secondary view doesn't resize when (eg) rotating the device

### ISSUE THREAD

**Issue by MitchBomcanhao** [AndreiMisiukevich/ExpandableView#21]
I'm trying to use ExpandableView to show a bit of text in the expanded view. This means that, depending on screen/window width and the length of the text, it can flow into several lines.

What I've found was that the secondary view's height is kept following the first initialisation of the view, so when I rotate the device it will either clip the content or show additional blank space.

![secondaryviewbug](https://user-images.githubusercontent.com/31066938/57009915-78d49980-6bf1-11e9-94e2-8dbe12c47dc5.png)

In order to get the control to work roughly as expected I have had to implement a few changes to the ExpandableView.cs class, adding this override for OnSizeAllocated.

``

        private double _previousWidth;

        protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height);

            if (width == _previousWidth)
            {
                //nothing to do
                return;
            }
            else if (this.Status != ExpandStatus.Expanded && this.Status != ExpandStatus.Expanding)
            {
                // secondaryview is not visible, we should reset it so that it'll appear in the correct size when active
                _lastVisibleHeight = -1;
            }
            else if ( this.Status != ExpandStatus.Collapsed && this.Status != ExpandStatus.Collapsing)
            {
                // secondaryview is visible, needs resizing to fit new width
                this.SecondaryViewHeightRequest = -1;
                this.ForceUpdateSize();
            }

            this._previousWidth = width;
        }

Out of a few attempts at fixing this, this was the most complete solution:
- it resizes on UWP when resizing the window.
- it resizes when rotating the device the secondary view is open.
- it resizes correctly when you open the view, close it and rotate the device/resize the window, then reopen the view.

I am very keen on using this control (nice work Andrei), but can't really do it without fixing this problem.
Am I close to a (good enough) fix for the problem or have I somehow not noticed how resizing is supposed to be handled?

Thanks

**Comment by AndreiMisiukevich** [comment]
Nice catch :)
Do you want to make PR or I should fix this issue myself ?

**Comment by MitchBomcanhao** [comment]
Well, my workaround isn't necessarily the neatest code, it's just where I got to to make it work - feel free to take the code, try it and change it if needed.

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao but maybe it would be enough (on status changed)
```csharp
case ExpandStatus.Expanded:
                        (exp.Parent.Parent as ScrollView).ScrollToAsync(exp.SecondaryView, ScrollToPosition.MakeVisible, true);
```

check:
http://www.giphy.com/gifs/J336TtoeNou0bHHCUV

**Comment by AndreiMisiukevich** [comment]
fixed

**Comment by MitchBomcanhao** [comment]
@AndreiMisiukevich 
Nice stuff getting a new package out :) But...

This fix doesn't work on Windows devices, as resizing the app window doesn't trigger a propertychanged event on deviceinfo (that only fires for device orientation changed?).

My initial fix was similar to yours (using Xamarin essentials to check for orientation), but then I tried it on windows (windowed app, haven't checked tablet mode) and it didn't get triggered either, so I tried the resize event which would cover all platforms.

Sadly, I haven't got a better suggestion at the moment...

edit: It also fails on the third scenario I've mentioned: open and close a secondary view, then rotate the device and open it again. The secondary view has been resized to a wrong height, usually a very small number (contents nearly invisible).

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao but you fix works well in all cases, correct?)

**Comment by MitchBomcanhao** [comment]
I think so...

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao so, we need to apply it :)
But to root Page, instead of view, i presume

What do you think?

**Comment by AndreiMisiukevich** [comment]
Look here: https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardView/CardsView.cs#L702-L709

**Comment by MitchBomcanhao** [comment]
I'm not sure what you mean by that. We care about is the control's width changing, not so much the parent page's width (a control may change width regardless of the overall page size, depending on your layout).

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao okay
But why you don't care about height changes (primary view height e.g)?

**Comment by MitchBomcanhao** [comment]
You're right - I am likely overlooking many scenarios, as expandableview can be used in many different layouts. I didn't care about height changes because I've made my layout consistent for the primaryview and only the secondaryview can have linebreaks in its content. I haven't seen how primary view reacts with similar content.
