### ISSUE TITLE
[Feature Request]: Scroll To Secondary View If Out Of Bounds

### ISSUE THREAD

**Issue by Nickprovs** [AndreiMisiukevich/ExpandableView#22]
My use case might be niche, I'm not sure. I only have one view I need to expand / collapse... except it's at the end of the ContentPage. As a result, when I select expand... the animation happens but is not in the user's viewport.

I solved this for myself by importing the ExpandableView directly into my project and adding another DependencyProperty called ContainingScrollViewer. If the user has set that, I scroll to the secondary view's start position in InvokeAnimation if the y + height of the secondary view is outside of the scrollviewer's viewport. After the scrollto, I RaiseStatusChanged and then return.

I'm not sure if this is a good solution for everybody.

**Comment by AndreiMisiukevich** [comment]
Hmm, could you please provide video ?)

**Comment by Nickprovs** [comment]
[Video Of Request](https://youtu.be/dttPG8pQOxE)

Here's an example of what I'm talking about. If you want to see what I did in more detail, let me know. As I said, I'm not sure how useful this will be to everyone else. To me, allowing the consumer to specify a containing scroll-viewer and scrolling to the secondary view if it at the bottom was ideal.

**Comment by AndreiMisiukevich** [comment]
@Nickprovs ahahah) cool video looooool))

**Comment by AndreiMisiukevich** [comment]
@Nickprovs anyway thanks for sharing idea :)

**Comment by AndreiMisiukevich** [comment]
@Nickprovs 
 but maybe it would be enough (on status changed)
```csharp
case ExpandStatus.Expanded:
                        (exp.Parent.Parent as ScrollView).ScrollToAsync(exp.SecondaryView, ScrollToPosition.MakeVisible, true);
```

check:
http://www.giphy.com/gifs/J336TtoeNou0bHHCUV

**Comment by Nickprovs** [comment]
> ```cs
> case ExpandStatus.Expanded:
>                         (exp.Parent.Parent as ScrollView).ScrollToAsync(exp.SecondaryView, ScrollToPosition.MakeVisible, true);
> ```
This is the better solution. I was trying to avoid code-behind but, to be honest... this is a special case and it's probably better to have some code in my page as oppose to the control.

The one major thing I'd change is to case on Expanding and not Expanded so there's no delay waiting for an animation that I can't see to finish. I tested casing on that and it works fine.

Thanks for your help :)

**Comment by AndreiMisiukevich** [comment]
@Nickprovs thank you too

**Comment by AndreiMisiukevich** [comment]
@Nickprovs if you like this plugin, you may star it))

**Comment by Nickprovs** [comment]
> @Nickprovs if you like this plugin, you may star it))

Done!
