### ISSUE TITLE
ScrollView Not showing in Sample Code

### ISSUE THREAD

**Issue by BicycleMark** [AndreiMisiukevich/ExpandableView#23]
Hello Andrei:
    In the ManyPageView I noticed the ScrollView was not showing. Do you have any idea as to why that would be?  

        public ManyViewsPage()
        {
            var mainStack = new StackLayout
            {
                Spacing = 15
            };

            for (int i = 0; i < 15; ++i)
            {
                mainStack.Children.Add(CreateExpandable(i));
            }

            BackgroundColor = Color.Olive;
            Content = new ScrollView
            {
                Padding = new Thickness(20, Device.RuntimePlatform == Device.iOS ? 20 : 0, 20, 0),
                Content = mainStack 
            };
        }
![Screen Shot 2019-05-07 at 8 01 20 AM](https://user-images.githubusercontent.com/11739690/57301998-d2c8d980-709f-11e9-8459-782c270b675b.png)

**Comment by AndreiMisiukevich** [comment]
What do you mean "ScrollView wasn't showing" ? Do you mean scroll bar ?

**Comment by AndreiMisiukevich** [comment]
Why do you think it doesn't appear?)
Can you scroll items ?)

**Comment by AndreiMisiukevich** [comment]
@BicycleMark works fine
![qw](https://user-images.githubusercontent.com/10124814/57487155-80aed080-72b8-11e9-903f-69a612a6a5a3.gif)

**Comment by BicycleMark** [comment]
right you are
