### ISSUE TITLE
Does ExpandableView Support BindingContext As Collection.

### ISSUE THREAD

**Issue by BicycleMark** [AndreiMisiukevich/ExpandableView#24]
Hello Andrei:
    I was trying to use as ListView replacement. The Control does not have ItemsSource as collection binding exposed entry point. In the example you just programmatically add Collection Items to the view. Is there an example floating around that binds in xaml to a Collection?

   Thanks for all your hard work.

Kind Regards,
Mark Wardell

**Comment by AndreiMisiukevich** [comment]
Unfortunately it's impossible to use ExpandableView in ListView

But you can use StackLayout as holder and use BindableLayout which was contributed by @andreinitescu (Hi Andrei haha)

more info: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts

**Comment by AndreiMisiukevich** [comment]
Something like that

```xaml
<StackLayout BindableLayout.ItemsSource="{Binding Items}">
    <BindableLayout.ItemTemplate>
        <exp:ExpandableView>
            .....
        </exp:ExpandableView>
    </BindableLayout.ItemTemplate>
</StackLayout>
```

**Comment by BicycleMark** [comment]
Thanks I will give it a whirl and possibly create a sample ContentPage Pull request for addition to the sample app

**Comment by AndreiMisiukevich** [comment]
@BicycleMark would be super :)
i look forward to see PR ))

**Comment by ali-h2010** [comment]
@AndreiMisiukevich , can i use bindable layout on the whole collapsing item to generate multiple expandable views at run time?
expandable:ExpandableView supports BindableLayout but i am not sure how to pass the layoutTemplate as ExpandableView takes ExpandableView.PrimaryView and ExpandableView.SecondaryViewTemplate

**Comment by ali-h2010** [comment]
When i tried the following, i got an error: 

Error: XLS0415: The attachable property 'PrimaryView' was not found in type 'ExpandableView'. 
Error: XLS0415: The attachable property 'SecondaryViewTemplate' was not found in type 'ExpandableView'.

```
<expandable:ExpandableView x:Name="expandableView" 
                           BackgroundColor="Red"
                           TouchHandlerView="{x:Reference arrow}"
                           CommandParameter="some text"
                           Command="{Binding Path=TapCommand, Source={x:Reference page}}"
                           ExpandAnimationLength="100">
             <BindableLayout.ItemTemplate>
                <DataTemplate>            
                    <expandable:ExpandableView.PrimaryView>
                        <StackLayout Orientation="Horizontal">
                            <Label Text="Expandable view" FontSize="30" VerticalTextAlignment="Center"/>
                            <Image x:Name="arrow" Source="arrow_drop_down.png" HeightRequest="60" WidthRequest="60" HorizontalOptions="EndAndExpand"/>
                        </StackLayout>
                    </expandable:ExpandableView.PrimaryView>
                    <expandable:ExpandableView.SecondaryViewTemplate>
                        <DataTemplate>
                            <StackLayout Padding="5">
                                <Label Text="Item" FontSize="Large"/>
                                <Label Text="Item" FontSize="Large"/>
                                <Label Text="Item" FontSize="Large"/>
                                <Label Text="Item" FontSize="Large"/>
                                <Label Text="Item" FontSize="Large"/>
                            </StackLayout>
                        </DataTemplate>
                    </expandable:ExpandableView.SecondaryViewTemplate>
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </expandable:ExpandableView>
```

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich , can i use bindable layout on the whole collapsing item to generate multiple expandable views at run time?
> expandable:ExpandableView supports BindableLayout but i am not sure how to pass the layoutTemplate as ExpandableView takes ExpandableView.PrimaryView and ExpandableView.SecondaryViewTemplate

Show me what are you trying to achieve

**Comment by AndreiMisiukevich** [comment]
Oh, your xaml in totally wrong

**Comment by ali-h2010** [comment]
I will try binding the stacklayout out that has the expandable view.
I will update you if that works.

**Comment by AndreiMisiukevich** [comment]
it should look like smth like that @ali-h2010 
```xaml
<StackLayout BindableLayout.ItemsSource={Binding Items}>
    <BindableLayout.ItemTemplate>
        <expandable:ExpandableView x:Name="expandableView" 
                   BackgroundColor="Red"
                   TouchHandlerView="{x:Reference arrow}"
                   CommandParameter="some text"
                   Command="{Binding Path=TapCommand, Source={x:Reference page}}"
                   ExpandAnimationLength="100">         
            <expandable:ExpandableView.PrimaryView>
                <StackLayout Orientation="Horizontal">
                    <Label Text="Expandable view" FontSize="30" VerticalTextAlignment="Center"/>
                    <Image x:Name="arrow" Source="arrow_drop_down.png" HeightRequest="60" WidthRequest="60" HorizontalOptions="EndAndExpand"/>
                </StackLayout>
            </expandable:ExpandableView.PrimaryView>
            <expandable:ExpandableView.SecondaryViewTemplate>
                <DataTemplate>
                    <StackLayout Padding="5">
                        <Label Text="Item" FontSize="Large"/>
                        <Label Text="Item" FontSize="Large"/>
                        <Label Text="Item" FontSize="Large"/>
                        <Label Text="Item" FontSize="Large"/>
                        <Label Text="Item" FontSize="Large"/>
                    </StackLayout>
                </DataTemplate>
            </expandable:ExpandableView.SecondaryViewTemplate>
        </expandable:ExpandableView>
    </BindableLayout.ItemTeamplate>
</StackLayout>
```

**Comment by ali-h2010** [comment]
@AndreiMisiukevich, Excellent, many thansk Mr. Andrei

**Comment by ali-h2010** [comment]
It's working perfectly
![Screen Shot 2020-02-24 at 3 38 28 PM](https://user-images.githubusercontent.com/12033261/75153191-d8210e80-571b-11ea-9cc0-264f6d860bae.png)

**Comment by AndreiMisiukevich** [comment]
> It's working perfectly
> ![Screen Shot 2020-02-24 at 3 38 28 PM](https://user-images.githubusercontent.com/12033261/75153191-d8210e80-571b-11ea-9cc0-264f6d860bae.png)

great )

**Comment by ali-h2010** [comment]
@AndreiMisiukevich, do you have any suggestion on how to hook the expanding event so i can change the icon accordingly or take an action? I know this is not suppose to be used in a bindable layout but this is my last challenge :)

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich, do you have any suggestion on how to hook the expanding event so i can change the icon accordingly or take an action? I know this is not suppose to be used in a bindable layout but this is my last challenge :)

I suggest using triggers (observe IsExpanded property). Or any other approach

**Comment by ali-h2010** [comment]
Just a small warning that i didn't notice before if you are planning to use bindable layouts:

> Bindable layouts should only be used when the collection of items to be displayed is small, and scrolling and selection isn't required. While scrolling can be provided by wrapping a bindable layout in a ScrollView, this is not recommended as bindable layouts lack UI virtualization. When scrolling is required, a scrollable view that includes UI virtualization, such as ListView or CollectionView, should be used. Failure to observe this recommendation can lead to performance issues.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts
