### ISSUE TITLE
TouchHandlerView Property and CommandProperty

### ISSUE THREAD

**Issue by BicycleMark** [AndreiMisiukevich/ExpandableView#25]
Hello Andrei:
   I have my application proven using ExpandableView. It is not, however working in true MVVM fashion. I fail/lockup when I attempt to attach a tapGesture to a Label inside the ExpandableView. I realize you have a sample AttachTapGestureToCustomViewPage. It never actually attaches a TapGesture... :)

   I have learned in my MVVM framework how to attach to expanding/collapsing view and getting the BindingContext and casting to VM type. then operating on my ViewModel in that manner from View.  my group of devs wants pure mvvm so this won't work for us.

Previously I had attempted attaching a gesture to an item inside the Expandable. primary view.... no  luck. the system locked up. 

here are my Questions related to achieving my goal.:

1) Can I turn touch handling off (**IsTouchToExpandEnabled**) and then safely without locking system.  Currently attach touchGesture is locking system?

2) What is **TouchHandlerViewPropefrty** about? 

3)  **Command Property** Looks inviting. However there is no **CommandParameter Property**

**Comment by AndreiMisiukevich** [comment]
@BicycleMark so, you need to expand your view by tapping on label. Is it correct?
(here is sample how to do it: https://github.com/AndreiMisiukevich/ExpandableView/blob/master/ExpandableViewSample/AttachTapGestureToCustomViewPage.xaml . no need it gestures)

TouchHandlerViewPropefrty allows to set "tap to expand" are (by default it's whole PrimaryView

CommandParameter - need to add)

**Comment by BicycleMark** [comment]
Hello Andrei:
   Thanks for your response.  /AttachTapGestureToCustomViewPage.xaml  actually does somethings that helped me work around my issue. My team wants me to call a command from the Gesture Recognizer. The Command is in the BindingContedxt. 

Incidentally it does not actually attach an actual TapGestureRecognizer

 <exp:ExpandableView.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding Path=BindingContext.SelectQuestionCommand, 
                                                          Source={x:Reference mainStack}}" 
                                                          CommandParameter="{Binding}" /></exp:ExpandableView.GestureRecognizers>

**Comment by AndreiMisiukevich** [comment]
Bind ExpandableViewCommand to your BindingContext.Command

**Comment by BicycleMark** [comment]
yes... but when I attach any TapGestureRecognizer it freezes.....

exp:ExpandableView.GestureRecognizers
</exp:ExpandableView.GestureRecognizers>

**Comment by BicycleMark** [comment]
excuse me I mean to say attach then tap

**Comment by AndreiMisiukevich** [comment]
@BicycleMark but you needn't have to add tapGestureRecognizer...

Share you sample and explain what you want to achieve. i will check help

**Comment by BicycleMark** [comment]
I will send something soon

**Comment by AndreiMisiukevich** [comment]
check sample again
I showed how to do some stuff on tap
