### ISSUE TITLE
Collapsing and expanding is leaving empty space where SecondaryView was

### ISSUE THREAD

**Issue by LeoJHarris** [AndreiMisiukevich/ExpandableView#26]
Hi @AndreiMisiukevich 

Android ONLY issue I am facing:

I've noticed what I think might be an issue/bug with the plugin. My setup is I have your component inside a ListView as the viewcell, and when I scroll down the screen (I do note that only scrolling down a little first and then expanding causes issues) and expand and collapse a row unfortunately it just makes the content invisible rather then collapsing the SecondaryView and leaves a large empty space where the SecondaryView was (see the GIF below):

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5468757/58215550-7e378680-7d4e-11e9-8e90-16bd8c737d41.gif)

I'm using:

ExpandableView: 1.0.9,
Xamarin Forms: 4.0.0.425677
Also I am using the new Xamarin.Forms.Visual.Material: 4.0.0.425677

Android Device is 5.1.1 (Galaxy Tab A 7.0 SM-T280),
I also have Target Android Version 9.0 (API Level 28) and minimum android version 5.0 (API Level 21)

**Comment by LeoJHarris** [comment]
Attached is a sample repo:

[SampleTest.zip](https://github.com/AndreiMisiukevich/ExpandableView/files/3210282/SampleTest.zip)

let me know if you have any issues

**Comment by AndreiMisiukevich** [comment]
See #27
