### ISSUE TITLE
Last item in list view - expanding not immediately allowing scroll to reveal secondary-view

### ISSUE THREAD

**Issue by LeoJHarris** [AndreiMisiukevich/ExpandableView#27]
Hi @AndreiMisiukevich 

This might be a bug issue (again have attached GIF of issue in action). Basically issue seems to occur when ExpandableView Item in ListView is the last item (scrolling down the page to that item is the only way to replicate as well) and when expanding does not immediately allow user to scroll down further to reveal the SecondaryView, rather what is required is to scroll up the page a certain amount and then down a few times before it expands and reveals the SecondaryView. 

You can see in the GIF below that I attempt to scroll down to show the collapsed SecondaryView but that  doesnt work initially without scrolling up and down a few times.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/5468757/58215765-89d77d00-7d4f-11e9-8b7b-2c483ad3575d.gif)

ExpandableView: 1.0.9,
Xamarin Forms: 4.0.0.425677
Also I am using the new Xamarin.Forms.Visual.Material: 4.0.0.425677

Android Device is 5.1.1 (Galaxy Tab A 7.0 SM-T280),
I also have Target Android Version 9.0 (API Level 28) and minimum android version 5.0 (API Level 21)

**Comment by LeoJHarris** [comment]
Attached is a sample repo:

[SampleTest.zip](https://github.com/AndreiMisiukevich/ExpandableView/files/3210282/SampleTest.zip)

let me know if you have any issues

**Comment by AndreiMisiukevich** [comment]
Thanks
i will check
but not sure, that expandableview can be used with listView

**Comment by LeoJHarris** [comment]
Thanks @AndreiMisiukevich 

Regarding ExpandableView working with ListView, this was working previously (this issue specifically). 

I have cloned your repo sample project and had the same issue.

See attached for ExpandableView in ListView with your sample project:

[ExpandableView-master (2).zip](https://github.com/AndreiMisiukevich/ExpandableView/files/3213681/ExpandableView-master.2.zip)

**Comment by LeoJHarris** [comment]
Okay so I have manage to solve this, turns out I was wrapping a ContentView around the ExpandableView in the ViewCell, the ContentView being the root parent view in the viewCell,

Once I removed that the issue went away.

As previously mentioned this didnt seem to be an issue, but has resolved my issue.

**Comment by LeoJHarris** [comment]
Okay so I think the need is to call ForceUpdateSize() on the viewcell when the StatusChange Changes.

```csharp
private async void onStatusChanged(object sender, StatusChangedEventArgs e)
        {
            if (e.Status == ExpandStatus.Collapsed || e.Status == ExpandStatus.Expanded)
            {
                if (e.Status == ExpandStatus.Collapsed)
                {
                    await arrowDropDownImage.RotateTo(0, 250, Easing.BounceIn).ConfigureAwait(false);
                }
                else if (e.Status == ExpandStatus.Expanded)
                {
                    await arrowDropDownImage.RotateTo(180, 250, Easing.BounceIn).ConfigureAwait(false);
                }
            }
            Device.BeginInvokeOnMainThread(() =>
            {
                this.ForceUpdateSize();
            });
        }
```

Can you confirm if this resolves on your end as well - applies to both issues I raised

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris hmm. i think it's big performance penalty..

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich Yes but there doesnt appear to be an alternative i think.

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris agreed..
does it solve another issue too?

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich yes regarding other issue. It solves that too. Although that was a strange issue, im not sure why that was occuring in the first place. As mentioned i believe it happens on last item in listview when no remaining space on screen to display is currently visible

Edit: sorry i meant https://github.com/AndreiMisiukevich/ExpandableView/issues/26
Yes this solved by forceupdatesize

**Comment by LeoJHarris** [comment]
@AndreiMisiukevich Im not sure if worth keeping issue open, although i might try switching to not use expandableview and just toggle visibility, but i think i may need to call forceupdatesize anyhow but i try with change. At least may not have performance issue withat method

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris i'm sure you will have to call forceUpdateSize anyway

just wonder, what will happen if you try CollectionView WITHOUT this method

**Comment by AndreiMisiukevich** [comment]
Thanks @LeoJHarris, this can be considered as workaround

```csharp
expandable.StatusChanged += OnStatusChanged;
..
private async void OnStatusChanged(object sender, StatusChangedEventArgs e)
{
    if (e.Status == ExpandStatus.Collapsed || e.Status == ExpandStatus.Expanded)
    {
        if (e.Status == ExpandStatus.Collapsed)
        {
            await arrowDropDownImage.RotateTo(0, 250, Easing.BounceIn).ConfigureAwait(false);
        }
        else if (e.Status == ExpandStatus.Expanded)
        {
            await arrowDropDownImage.RotateTo(180, 250, Easing.BounceIn).ConfigureAwait(false);
        }
    }
    Device.BeginInvokeOnMainThread(() => ForceUpdateSize());
}
```
