### ISSUE TITLE
Expand an item one at a time

### ISSUE THREAD

**Issue by MrMayTwenty** [AndreiMisiukevich/ExpandableView#29]
Hi I just tried this out and experimenting this .
But i can't figure out a way to contract once a new item is selected.

My expandableView is inside a stacklayout with bindablelayout enabled 
and tried to change the value of the IsExpanded bindable property through command in a viewmodel

**Comment by MrMayTwenty** [comment]
Never mind, forgot the property changed listener

**Comment by AndreiMisiukevich** [comment]
Great )
Sorry I am on vacation.
