### ISSUE TITLE
Can you add SecondaryView for xaml?

### ISSUE THREAD

**Issue by jingliancui** [AndreiMisiukevich/ExpandableView#30]
Now i want do some customized layout or some animation in your control but it's must use SecondaryViewTemplate.

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/ExpandableView/blob/master/ExpandableView/ExpandableView.cs#L43-L49

there are properties for animation customization.
as for custom layout. Put your desired view inside SecondaryViewTemplate.

I don't see any reason for adding SecondaryView
