### ISSUE TITLE
Cell is overlapping on each other.

### ISSUE THREAD

**Issue by Naveen9453** [AndreiMisiukevich/ExpandableView#31]
When I am using ExpandbleView as a cell of ListView inside ListView.ItemTemplate 
and on click I want to expand the cell but when I am expanding  the layout, it over-lapping on top of below item cell.

Can you Please give me some suggestion how to resolve this.

**Comment by AndreiMisiukevich** [comment]
try to call ForceUpdateSize (of cell and expandable view)
