### ISSUE TITLE
gif not shown

### ISSUE THREAD

**Issue by frankkkkkkkkkkkk** [AndreiMisiukevich/ExpandableView#34]
Hi,
thanks for your great component. I have a problem with the new XamarinForms4.4 gifs. My gif is invisible inside your component. What am I doing wrong? 

 `<Expandable:ExpandableView.SecondaryViewTemplate>`
`                            <DataTemplate>`
`                                <StackLayout>`
`                                    <Image Source="imageAsPngIsShown.png" />`
`                                    <Image Source="imageAsGifIsNotShown.gif" IsAnimationPlaying="True"/>`

**Comment by AndreiMisiukevich** [comment]
Hi, is it visible without expandable?

**Comment by frankkkkkkkkkkkk** [comment]
Sorry, my fault. It works now.

(With IsExpanded=false, the height of the secondaryview was not shown completly. I added image-heightrequest and now it works.)
