### ISSUE TITLE
[Enhancement] Add OnExpanding and OnCollapsing events.

### ISSUE THREAD

**Issue by RyanGaudion** [AndreiMisiukevich/ExpandableView#35]
Please can you expose these 2 events in the xaml as they would help me change visualelements based upon the status of the expander. 

I know there is an IsExpanded bool, but is there anyway to send events when this property changes?

Thank you in advance

**Comment by AndreiMisiukevich** [comment]
Hi)
Doesn't **StatusChanged** work for you?

**Comment by AndreiMisiukevich** [comment]
Expanding & Collapsing

**Comment by RyanGaudion** [comment]
My mistake. Thank you
