### ISSUE TITLE
Second ExpanderView PrimaryView height issue when First Status changes to Expanded iOS - CollectionView

### ISSUE THREAD

**Issue by pmahend1** [AndreiMisiukevich/ExpandableView#36]
```xml
<CollectionView
    ItemsSource="{Binding Items}"
    VerticalOptions="StartAndExpand"
    ItemSizingStrategy="MeasureAllItems">
    <CollectionView.ItemsLayout>
        <LinearItemsLayout
            Orientation="Vertical"
            ItemSpacing="0" />
    </CollectionView.ItemsLayout>
<CollectionView.ItemTemplate>
</CollectionView.ItemTemplate>
</CollectionView>
```

```xml
<expander:ExpandableView StateChanged="ExpandableViewStatusChanged">
    <expander:ExpandableView.PrimaryView>
        <Grid
            RowSpacing="0">
            <Grid.RowDefinitions>
                <RowDefinition
                    Height="Auto" />
                <RowDefinition
                    Height="40" />
                <RowDefinition
                    Height="Auto" />
            </Grid.RowDefinitions>
            <BoxView
                HeightRequest="1"
                BackgroundColor="Gray"
                Grid.Row="0" />
            <StackLayout
                x:Name="sl"
                Spacing="0"
                Orientation="Horizontal"
                Grid.Row="1">
                <Label
                    Margin="20,0,0,0"
                    x:Name="plusMinus"
                    Text="+"
                    VerticalTextAlignment="Center" />
                <Label
                    Text="{Binding Title}"
                    Margin="10,0,0,0"
                    TextColor="Green"
                    VerticalOptions="Center"
                    VerticalTextAlignment="Center"
                    HorizontalOptions="Start" />
            </StackLayout>
            <BoxView
                HeightRequest="1"
                BackgroundColor="Gray"
                Grid.Row="2" />
        </Grid>
    </expander:ExpandableView.PrimaryView>
    <expander:ExpandableView.SecondaryViewTemplate>
        <DataTemplate>
            <Label
                Padding="30,10"
                Text="{Binding Detail}"
                VerticalOptions="Start"
                VerticalTextAlignment="Center" />
        </DataTemplate>
    </expander:ExpandableView.SecondaryViewTemplate>
</expander:ExpandableView>

</DataTemplate>
```

```csharp
private void ExpandableViewStatusChanged(object sender, StatusChangedEventArgs args)
{
    if (sender is ExpandableView expander)
    {
        if (expander.PrimaryView is Grid grid)
        {
            if (grid.FindByName("sl") is StackLayout titleStackLayout)
            {
                if (titleStackLayout.Children[0] is Label icon && titleStackLayout.Children[1] is Label titleText)
                {
                    if (args.Status == ExpandStatus.Expanding)
                    {
                        Device.BeginInvokeOnMainThread(() => {
                            titleStackLayout.BackgroundColor = Color.Green;
                            icon.Text = "-";

                            icon.TextColor = Color.White;
                            titleText.TextColor = Color.White;
                        });

                    }
                    else if (args.Status == ExpandStatus.Collapsing)
                    {
                        Device.BeginInvokeOnMainThread(() => {
                            titleStackLayout.BackgroundColor = Color.White;
                            icon.Text = "+";

                            icon.TextColor = Color.Green;
                            titleText.TextColor = Color.Green;
                        });


                    }

                }
            }
        }


    }

}
```
#### Only 1st item selected(look at Item2 height) - this is wrong 

<img width="351" alt="image" src="https://user-images.githubusercontent.com/21352870/78832738-c5a42100-79b9-11ea-8d8e-86bef247cdd4.png">

#### None expanded
<img width="289" alt="image" src="https://user-images.githubusercontent.com/21352870/78832726-be7d1300-79b9-11ea-85b5-029dbe73f40b.png">

#### all 3 expanded
<img width="324" alt="image" src="https://user-images.githubusercontent.com/21352870/78833137-5ed33780-79ba-11ea-8661-0472dfe40cee.png">

#### middle only expanded
<img width="343" alt="image" src="https://user-images.githubusercontent.com/21352870/78833007-2fbcc600-79ba-11ea-8dc1-5df126d1cbee.png">

#### last 2 expanded  
<img width="332" alt="image" src="https://user-images.githubusercontent.com/21352870/78833131-5a0e8380-79ba-11ea-911a-1243e916259d.png">  

#### last only expanded   
<img width="302" alt="image" src="https://user-images.githubusercontent.com/21352870/78833204-78747f00-79ba-11ea-9618-62a1e8b18589.png">

Tried calling expander.ForceUpdateSize() and (expander.PrimaryView as Grid).ForceLayout()  but dint work as expected.

### Android
<img width="326" alt="image" src="https://user-images.githubusercontent.com/21352870/78832965-22074080-79ba-11ea-88ab-97e57c311846.png">

On android it is fine.

**Comment by AndreiMisiukevich** [comment]
Hi, thanks for the feedback.
I assume it's a complex issue (Expander + CollectionView).

Also, I suggest you use **Expander** from the latest pre-release Xamarin.Forms.
*Note*: don't forget to add "Expander_Experimenta" flag.

https://github.com/xamarin/Xamarin.Forms/issues/10230

Or maybe try "<CollectionView ItemSizingStrategy="MeasureAllItems" "

**Comment by pmahend1** [comment]
@AndreiMisiukevich  I have used MeasureAllItems

I dont want to use unstable pre release of Xamarin forms because this will be production released 

Is the Xamarin.Forms.Expander based off of this repo?

**Comment by pmahend1** [comment]
Update

As mentioned in other posts using `BindableLayout` with `StackLayout` fixed this issue
Only drawback was `ItemTemplateSelctor` `BindableObject` container doesn't expose `ItemsSource` to do manipulation.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich I have used MeasureAllItems
> 
> I dont want to use unstable pre release of Xamarin forms because this will be production released
> 
> Is the Xamarin.Forms.Expander based off of this repo?

Yes, that control is based on this one.

**Comment by AndreiMisiukevich** [comment]
> Update
> 
> As mentioned in other posts using `BindableLayout` with `StackLayout` fixed this issue
> Only drawback was `ItemTemplateSelctor` `BindableObject` container doesn't expose `ItemsSource` to do manipulation.

Why?

```csharp
var stack = new StackLayout();
var source = BindableLayout.GetItemsSource(stack);
```

**Comment by pmahend1** [comment]
@AndreiMisiukevich Thanks!
