### ISSUE TITLE
NaNis not valid for height in IOS

### ISSUE THREAD

**Issue by karen-yu-ysk** [AndreiMisiukevich/ExpandableView#37]
I implement many expandable view in one form. When click the expand arrow of expandable view, the error of "NaN is not valid for height in IOS" will show and the app crash. It is random pattern for the error, sometime will trigger the error when click expandable view "A", sometime will trigger the error when click expandable view "B"...

**Comment by karen-yu-ysk** [comment]
Sample code like this:

     <expandable:ExpandableView HorizontalOptions="FillAndExpand"
                                       TouchHandlerView="{x:Reference ExpandableListArrow}"
                                       ExpandAnimationLength="0"
                                       CollapseAnimationLength="0">

                <expandable:ExpandableView.PrimaryView>
                    <StackLayout Orientation="Horizontal"
                                 Spacing="0"
                                 HorizontalOptions="FillAndExpand">
                        <Label Text="Expandable View"
                               FontAttributes="Bold"/>
                        <Image x:Name="ExpandableListArrow"
                               Source="icon_arrow_down"
                               HorizontalOptions="EndAndExpand"
                               VerticalOptions="Start" />
                    </StackLayout>
                </expandable:ExpandableView.PrimaryView>

                 <expandable:ExpandableView.SecondaryViewTemplate>
                    <DataTemplate>
                        <StackLayout Orientation="Vertical"
                                     Spacing="0"
                                     HorizontalOptions="FillAndExpand">
                            <Label Text="View Name"
                                   HorizontalOptions="Start"/>

                            <StackLayout Orientation="Vertical"
                                         Spacing="0"
                                         HorizontalOptions="FillAndExpand"
                                         VerticalOptions="FillAndExpand"
                                         BindableLayout.ItemsSource="{Binding SampleList}">
                                <BindableLayout.ItemTemplate>
                                    <DataTemplate>
                                        <Grid HorizontalOptions="FillAndExpand"
                                              ColumnSpacing="18"
                                              RowSpacing="25"
                                              Margin="0,0,0,35">
                                            <Grid.RowDefinitions>
                                                <RowDefinition Height="Auto"/>
                                                <RowDefinition Height="Auto"/>
                                            </Grid.RowDefinitions>
                                            <Grid.ColumnDefinitions>
                                                <ColumnDefinition Width="*"/>
                                                <ColumnDefinition Width="*"/>
                                                <ColumnDefinition Width="*"/>
                                                <ColumnDefinition Width="*"/>
                                            </Grid.ColumnDefinitions>
                                            <StackLayout Spacing="0"
                                                         Grid.Row="0"
                                                         Grid.ColumnSpan="4"
                                                         Orientation="Vertical"
                                                         HorizontalOptions="FillAndExpand">
                                            </StackLayout>
                                        <Label Grid.Row="1"
                                                    Grid.ColumnSpan="2"
                                                    Text="Label 1"/>
                                         <Label Grid.Row="1"
                                                    Grid.Column="2"
                                                    Text="Label 2"/>
                                         <Label Grid.Row="1"
                                                    Grid.Column="3"
                                                    Text="Label 3"/>
                                     </Grid>
                                    </DataTemplate>
                                </BindableLayout.ItemTemplate>
                            </StackLayout>
                         <Button Text="Button" 
                                       VerticalOptions="EndAndExpand"/>
                      </StackLayout>
                    </DataTemplate>
                </expandable:ExpandableView.SecondaryViewTemplate>. 
    </expandable:ExpandableView>

**Comment by AndreiMisiukevich** [comment]
Hi @karen-yu-ysk have your already tried Expander from **Xamarin.Forms**? We merged this control there

**Comment by karen-yu-ysk** [comment]
@AndreiMisiukevich I have tried Expander from Xamain.Forms. But if showing the empty view in
the list, will throw NaN is not valid for height in IOS.

       <Expander HorizontalOptions="FillAndExpand"
                     ExpandAnimationLength="0"
                     CollapseAnimationLength="0">
            <Expander.Header>
                <StackLayout Orientation="Horizontal"
                             Spacing="0"
                             HorizontalOptions="FillAndExpand">
                    <Label Text="Expandable View"
                           FontAttributes="Bold"/>
                    <Image x:Name="ExpandableListArrow"
                               Source="icon_arrow_down"
                               HorizontalOptions="EndAndExpand"
                               VerticalOptions="Start">
                            <Image.Triggers>
                                <DataTrigger TargetType="Image"
                                             Binding="{Binding Source={RelativeSource AncestorType={x:Type Expander}}, Path=IsExpanded}"
                                             Value="True">
                                    <Setter Property="Source"
                                            Value="icon_arrow_up" />
                                </DataTrigger>
                            </Image.Triggers>
                        </Image>
                </StackLayout>
            </Expander.Header>

             <Expander.ContentTemplate>
                <DataTemplate>
                    <StackLayout Orientation="Vertical"
                                 Spacing="0"
                                 HorizontalOptions="FillAndExpand">
                        <Label Text="View Name"
                               HorizontalOptions="Start"/>

                        <StackLayout Orientation="Vertical"
                                     Spacing="0"
                                     HorizontalOptions="FillAndExpand"
                                     VerticalOptions="FillAndExpand"
                                     BindableLayout.ItemsSource="{Binding SampleList}">
                             <BindableLayout.EmptyView>
                                    <Label Text="Empty View"
                                               Margin="0,24,0,0"/>
                             </BindableLayout.EmptyView>
                            <BindableLayout.ItemTemplate>
                                <DataTemplate>
                                    <Grid HorizontalOptions="FillAndExpand"
                                          ColumnSpacing="18"
                                          RowSpacing="25"
                                          Margin="0,0,0,35">
                                        <Grid.RowDefinitions>
                                            <RowDefinition Height="Auto"/>
                                            <RowDefinition Height="Auto"/>
                                        </Grid.RowDefinitions>
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="*"/>
                                            <ColumnDefinition Width="*"/>
                                            <ColumnDefinition Width="*"/>
                                            <ColumnDefinition Width="*"/>
                                        </Grid.ColumnDefinitions>
                                        <StackLayout Spacing="0"
                                                     Grid.Row="0"
                                                     Grid.ColumnSpan="4"
                                                     Orientation="Vertical"
                                                     HorizontalOptions="FillAndExpand">
                                        </StackLayout>
                                    <Label Grid.Row="1"
                                                Grid.ColumnSpan="2"
                                                Text="Label 1"/>
                                     <Label Grid.Row="1"
                                                Grid.Column="2"
                                                Text="Label 2"/>
                                     <Label Grid.Row="1"
                                                Grid.Column="3"
                                                Text="Label 3"/>
                                 </Grid>
                                </DataTemplate>
                            </BindableLayout.ItemTemplate>
                        </StackLayout>
                     <Button Text="Button" 
                                   VerticalOptions="EndAndExpand"/>
                  </StackLayout>
                </DataTemplate>
            </Expander.ContentTemplate>
      </Expander>

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich I have tried Expander from Xamain.Forms. But if showing the empty view in
> the list, will throw NaN is not valid for height in IOS.
> 
> ```
>         <Expander.Header>
>             <StackLayout Orientation="Horizontal"
>                          Spacing="0"
>                          HorizontalOptions="FillAndExpand">
>                 <Label Text="Expandable View"
>                        FontAttributes="Bold"/>
>                 <Image x:Name="ExpandableListArrow"
>                            Source="icon_arrow_down"
>                            HorizontalOptions="EndAndExpand"
>                            VerticalOptions="Start">
>                         <Image.Triggers>
>                             <DataTrigger TargetType="Image"
>                                          Binding="{Binding Source={RelativeSource AncestorType={x:Type Expander}}, Path=IsExpanded}"
>                                          Value="True">
>                                 <Setter Property="Source"
>                                         Value="icon_arrow_up" />
>                             </DataTrigger>
>                         </Image.Triggers>
>                     </Image>
>             </StackLayout>
>         </Expander.Header>
> 
>          <Expander.ContentTemplate>
>             <DataTemplate>
>                 <StackLayout Orientation="Vertical"
>                              Spacing="0"
>                              HorizontalOptions="FillAndExpand">
>                     <Label Text="View Name"
>                            HorizontalOptions="Start"/>
> 
>                     <StackLayout Orientation="Vertical"
>                                  Spacing="0"
>                                  HorizontalOptions="FillAndExpand"
>                                  VerticalOptions="FillAndExpand"
>                                  BindableLayout.ItemsSource="{Binding SampleList}">
>                          <BindableLayout.EmptyView>
>                                 <Label Text="Empty View"
>                                            Margin="0,24,0,0"/>
>                          </BindableLayout.EmptyView>
>                         <BindableLayout.ItemTemplate>
>                             <DataTemplate>
>                                 <Grid HorizontalOptions="FillAndExpand"
>                                       ColumnSpacing="18"
>                                       RowSpacing="25"
>                                       Margin="0,0,0,35">
>                                     <Grid.RowDefinitions>
>                                         <RowDefinition Height="Auto"/>
>                                         <RowDefinition Height="Auto"/>
>                                     </Grid.RowDefinitions>
>                                     <Grid.ColumnDefinitions>
>                                         <ColumnDefinition Width="*"/>
>                                         <ColumnDefinition Width="*"/>
>                                         <ColumnDefinition Width="*"/>
>                                         <ColumnDefinition Width="*"/>
>                                     </Grid.ColumnDefinitions>
>                                     <StackLayout Spacing="0"
>                                                  Grid.Row="0"
>                                                  Grid.ColumnSpan="4"
>                                                  Orientation="Vertical"
>                                                  HorizontalOptions="FillAndExpand">
>                                     </StackLayout>
>                                 <Label Grid.Row="1"
>                                             Grid.ColumnSpan="2"
>                                             Text="Label 1"/>
>                                  <Label Grid.Row="1"
>                                             Grid.Column="2"
>                                             Text="Label 2"/>
>                                  <Label Grid.Row="1"
>                                             Grid.Column="3"
>                                             Text="Label 3"/>
>                              </Grid>
>                             </DataTemplate>
>                         </BindableLayout.ItemTemplate>
>                     </StackLayout>
>                  <Button Text="Button" 
>                                VerticalOptions="EndAndExpand"/>
>               </StackLayout>
>             </DataTemplate>
>         </Expander.ContentTemplate>. 
> ```

Do you experience the same exceptions if you use Expander with StackLayout + ScrollView? (Probably there are some troubles with ListView+Expander)
