### ISSUE TITLE
Add Status and StatusChanged event

### ISSUE THREAD

**Issue by LeoJHarris** [AndreiMisiukevich/ExpandableView#4]
Hi great piece of control, question or enhancement is it possible to be notified when the expandable View is fully open and showing the secondary window. I want to run a task in the secondary view once it is fully open but right now while the secondary view is opening its freezing/slowing the UI while the secondary view is opening

**Comment by AndreiMisiukevich** [comment]
Hi, obviously, there are several possible tricks/workarounds for achieving it) (like comparing secondaryView heigh with expected height or awaiting some delay etc)
But I think, we should create proper pretty way :)

Now we have only **IsExpandChanged** event.
I am keen to extend the view with
1) IsExpandChangedCommand
2) Status property (Opened, Closed, Opening, Closing)
3) StatusChanedEvent
4) StatusChangedCommand

What do you think ?

**Comment by LeoJHarris** [comment]
Hey I think StatusChangedEvent be best. Notify the subscriber when Opened, Closed, Opening and closing.

At this stage IsExpandChanged is called in the beginning stage of opening or closing but like the Rg.Plugins.Popup plugin that has OnAppearingAnimationEndAsync that can be overridden after page appeared. We should have a event that after secondary view is Appeared / open or Disappeared / closed in additions to opening and closing. Work is better delegated after the view is visible then during the opening phase

**Comment by AndreiMisiukevich** [comment]
I think, if we add StatusChangedEvent, we will be able to remove IsExpandedChanged as it will be redundant

**Comment by LeoJHarris** [comment]
StatusChangedEvent replaces IsExpandedChanged. 👍 With 4 possible status's

**Comment by AndreiMisiukevich** [comment]
1.0.2 version
