### ISSUE TITLE
Compatibility with Xamarin Forms 3.4 

### ISSUE THREAD

**Issue by npagare** [AndreiMisiukevich/ExpandableView#5]
Hi @AndreiMisiukevich , great plugin to use.

Is this plugin compatible with XF v 3.4 ?

Thanks

**Comment by AndreiMisiukevich** [comment]
@IoTFier hi, haven't tried, but, for sure, yes, it should work for ALL new XF versions

Does it work?

**Comment by LeoJHarris** [comment]
Using xamarin.forms 3.4 works fine on android, untested on iOS

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris great ) thanks
Should work the same on iOS
