### ISSUE TITLE
Primary and secondary views sharing the same width always.

### ISSUE THREAD

**Issue by LeoJHarris** [AndreiMisiukevich/ExpandableView#6]
Regarding the Primary and secondary view UI customization. If I wanted to create a primary View to be say a simple icon with a height and width of 50 in a frame along bottom of the page and I wanted the secondary View to be a more complex UI with a list view spanning the entire screen horizontally and some set height etc, see attached;. Is this possible? 

When I try the above the primary view is always the width of the secondary which is full screen width however I only want the Primary to be a icon in a frame or something and the secondary to be full width etc. Is it possible to create views independent of each other with regards to this?

![untitled](https://user-images.githubusercontent.com/5468757/49347589-c01f3280-f704-11e8-8142-1db742f4c1f9.png)

**Comment by AndreiMisiukevich** [comment]
@LeoJHarris hi, it can be great enhancement
But for now you can 
- add small icon with tapGesture
- add expandable view with PrimaryView IsVisible = false or HeightRequest = 0
- expand/collapse expandalbe view by icon click

**Comment by AndreiMisiukevich** [comment]
Hi, i could reproduce desired behavior on the sample project

![image](https://user-images.githubusercontent.com/10124814/50113778-fa83e600-0253-11e9-80ac-f6bb09f04c82.png)
