### ISSUE TITLE
Nested ExpandableView

### ISSUE THREAD

**Issue by RicardoMoraisPOR** [AndreiMisiukevich/ExpandableView#8]
Is it possible to have an ExpandableView inside another ExpandableView? and if so how can i achive it?
Example Code:

XAML
```
<expandable:ExpandableView>
    <expandable:ExpandableView.PrimaryView>
        <StackLayout BackgroundColor="Black" HeightRequest="200">

        </StackLayout>
    </expandable:ExpandableView.PrimaryView>
    <expandable:ExpandableView.SecondaryViewTemplate>
        <DataTemplate>
            <expandable:ExpandableView>
                <expandable:ExpandableView.PrimaryView>
                    <StackLayout BackgroundColor="Green" HeightRequest="200">

                    </StackLayout>
                </expandable:ExpandableView.PrimaryView>
                <expandable:ExpandableView.SecondaryViewTemplate>
                    <DataTemplate>
                        <StackLayout BackgroundColor="Blue" HeightRequest="200">

                        </StackLayout>
                    </DataTemplate>
                </expandable:ExpandableView.SecondaryViewTemplate>
            </expandable:ExpandableView>
        </DataTemplate>
    </expandable:ExpandableView.SecondaryViewTemplate>
</expandable:ExpandableView>
```
I can only access the "green" StackLayout, the secondary data for that StackLayout doesn't open (the "blue" StackLayout), is this an expected behaviour?

EDIT: If i set `IsExpanded=true` in the inside ExpandableView, i can see that the animation happens, but not the expanding

**Comment by AndreiMisiukevich** [comment]
Hi @RicardoMoraisPOR Have you tried to set **SecondaryViewHeightRequest** of expandableView property ?

**Comment by RicardoMoraisPOR** [comment]
@AndreiMisiukevich Yes and i think i just figure out what's happening, if i set **SecondaryViewHeightRequest** with 400 (each stack on my example as 200) i get something like this:

___________
Primary (black)
___________
Secondary (green)

//white space
___________

that way it gives enough space so that when i click in the "green" StackLayout the blue StackLayout can be shown:

___________
Primary (black)
___________
Secondary (green)
___________
Secondary(of secondary) (blue)
___________

but that way it leaves me with a big white space in the first SecondaryView , any ideas how can i update the height while keeping the animation feeling?

**Comment by AndreiMisiukevich** [comment]
@RicardoMoraisPOR Good question =\ have no idea yet.

**Comment by RicardoMoraisPOR** [comment]
@AndreiMisiukevich i will keep trying to find an solution , thank you for your time

**Comment by AndreiMisiukevich** [comment]
@RicardoMoraisPOR Hi, did you try?)

**Comment by RicardoMoraisPOR** [comment]
> @RicardoMoraisPOR Hi, did you try?)

I didn't find any workaround, since the project has a deadline, we dropped the idea for a nested expandable view, sorry. 
This is a very niche problem, but i will comeback and try to solve this

**Comment by AndreiMisiukevich** [comment]
Closing for now. Maybe return later.
For now i am not keen to support nested expandable view.

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/ExpandableView/issues/19
